---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Libraries
```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
})
```

## Paths

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

## Load data
```{r}
res_dir <- paste0(proj_dir, "/data/stamp_6/CTC_1/processed")
sce <- qread(glue("{res_dir}/raw_sce.qs"))
```


# Remove cells at the border of the mask

```{r}
xmin <- 1000
xmax <- 8500
ymin <- 700
ymax <- 8300
```

```{r}
df <- as.data.frame(colData(sce))

gg_mask <- ggplot(df, aes(x = x_centroid, y = y_centroid)) +
            geom_point(size = 0.001) +
            theme_minimal() + 
            geom_vline(xintercept = c(xmin,xmax), col = "red")+ 
            geom_hline(yintercept = c(ymin,ymax), col = "red") +
            labs(x = "", y = "")
```

```{r}
sce_filt <- sce[,sce$x_centroid > xmin & sce$x_centroid < xmax & sce$y_centroid > ymin & sce$y_centroid < ymax]
```

```{r}
ncol(sce)
ncol(sce_filt)
```

```{r}
gg_mask <- gg_mask + 
            labs(title = "Stamp 6 - PBMCs & n=20 CTCs", 
                 subtitle = glue("Raw: {number(ncol(sce), big.mark = '.')}, Filtered: {number(ncol(sce_filt), big.mark = '.')}")) 
```

# Add QC metrics
```{r}
sce <- sce_filt
sce <- addPerCellQCMetrics(sce)
```

## Remove empty cells
```{r}
sce <- sce[,sce$sum > 0 & sce$detected > 0]
```

```{r}
sce
```


## QC thresholds
```{r}
feat_lthr <- 5
tcount_lthr <- 5

cccounts_hthr <- 1
cpcounts_hthr <- 1


carea_lthr <- 10
#carea_hthr <- 80

narea_lthr <- 10
narea_hthr <- 80
```


```{r}
discard_carea <-  sum(sce$cell_area < carea_lthr)
discard_narea <-  sum(sce$nucleus_area < narea_lthr | sce$nucleus_area > narea_hthr, na.rm = T)

discard_tcounts <- sum(sce$transcript_counts < tcount_lthr)
discard_cccounts <- sum(sce$control_codeword_counts > cccounts_hthr)
discard_cpcounts <- sum(sce$control_probe_counts > cpcounts_hthr) 

discard_carea_id <- unique(sce$cell_id[sce$cell_area < carea_lthr])
discard_narea_id <- unique(sce$cell_id[sce$nucleus_area < narea_lthr | sce$nucleus_area > narea_hthr])

discard_tcounts_id <- unique(sce$cell_id[sce$transcript_counts < tcount_lthr])
discard_cccounts_id <- unique(sce$cell_id[sce$control_codeword_counts > cccounts_hthr])
discard_cpcounts_id <- unique(sce$cell_id[sce$control_probe_counts > cpcounts_hthr])
```

# Calculate percentage of discard for each filter
```{r}
calc_pct <- function(discard) {
  round(discard / n_distinct(sce$cell_id) * 100, 2)
}

discard_carea_pct <- calc_pct(discard_carea)
discard_narea_pct <- calc_pct(discard_narea)
discard_tcounts_pct <- calc_pct(discard_tcounts)
discard_cccounts_pct <- calc_pct(discard_cccounts)
discard_cpcounts_pct <- calc_pct(discard_cpcounts)
```


```{r}
cellsdata <- as.data.frame(colData(sce))
```


## 1. Counts
```{r}
wh(15,5)
gg_counts <- wrap_plots(

# Transcripts
ggplot(cellsdata, aes(x = transcript_counts)) + 
  geom_histogram() + 
  scale_x_log10() +
  theme(legend.position = "right",
        axis.text = element_text(size = 15, color = "black")) +
  geom_vline(xintercept = tcount_lthr, col = "red", lty = 2) +
  labs(title = glue("Median Transcript counts: {median(cellsdata$transcript_counts)}"), x = "transcript_counts", y = "nCells",
       subtitle = glue("Discard: {discard_tcounts} / {discard_tcounts_pct}%")) +
  theme_minimal(),

# Control Probes

ggplot(cellsdata, aes(x = control_probe_counts)) + 
  geom_histogram() + 
  theme(legend.position = "right",
        axis.text = element_text(size = 15, color = "black")) +
  geom_vline(xintercept = cpcounts_hthr, col = "red", lty = 2) +
  labs(title = glue("Median ControlProbeCounts: {median(cellsdata$control_probe_counts)}"), x = "control_probe_counts", y = "nCells",
       subtitle = glue("Discard: {discard_cpcounts} / {discard_cpcounts_pct}%")) +
  theme_minimal(),

# Control Codewords
ggplot(cellsdata, aes(x = control_codeword_counts)) + 
  geom_histogram() + 
  theme(legend.position = "right",
        axis.text = element_text(size = 15, color = "black")) +
  geom_vline(xintercept = 0.9, col = "red", lty = 2) +
  labs(title = glue("Median ControlCodewordsCounts: {median(cellsdata$control_codeword_counts)}"), x = "control_codeword_counts", y = "nCells",
       subtitle = glue("Discard: {discard_cccounts} / {discard_cccounts_pct}%")) +
  theme_minimal(),

  ncol = 3
)
```


```{r}
gg_counts
```

## 2. Area
```{r}
gg_areas <- wrap_plots(

# Cell area
ggplot(cellsdata, aes(x = cell_area)) + 
  geom_histogram() + 
  theme(legend.position = "right",
        axis.text = element_text(size = 15, color = "black")) +
  geom_vline(xintercept = carea_lthr, col = "red", lty = 2) +
  labs(title = glue("Median Cell Area : {round(median(cellsdata$cell_area),2)}"), x = "cell_area", y =
        "nCells",
       subtitle = glue("Discard: {discard_carea} / {discard_carea_pct}%")) +
  theme_minimal(),

# Nucleus area
  ggplot(cellsdata, aes(x = nucleus_area)) + 
  geom_histogram() + 
  theme(legend.position = "right",
        axis.text = element_text(size = 15, color = "black")) +
  geom_vline(xintercept = c(narea_lthr,narea_hthr), col = "red", lty = 2) +
  labs(title = glue("Median Nucleus Area : {round(median(cellsdata$nucleus_area, na.rm = T),2)}"), x =
         "nucleus_area", y = "nCells",
       subtitle = glue("Discard: {discard_narea} / {discard_narea_pct}%")) +
  theme_minimal(),
 
ncol = 2)
```


```{r}
gg_areas
```

## 3. Features
```{r}
discard_feats <- sum(sce$detected < feat_lthr) 

discard_feats_id <- unique(sce$cell_id[sce$detected < feat_lthr])
```


```{r}
df <- as.data.frame(colData(sce))
```


```{r}
gg_feats <- ggplot(df, aes(x = detected)) + 
  geom_histogram() + 
  scale_x_log10() +
  theme(legend.position = "right",
        axis.text = element_text(size = 15, color = "black")) +
  geom_vline(xintercept = feat_lthr, col = "red", lty = 2) +
  labs(title = glue("Median nFeatures: {median(df$detected)}"), x = "nFeatures", y = "nCells",
       subtitle = glue("Discard: {discard_feats} ")) +
  theme_minimal()
```

```{r}
gg_b <- wrap_plots(gg_feats, gg_areas, ncol =2) + plot_layout(widths = c(1,2))
```

# Combined plots
```{r}
vectors_to_intersect <- list(discard_carea_id, discard_narea_id, discard_tcounts_id, discard_cccounts_id, discard_cpcounts_id, discard_feats_id)

# Intersect all vectors
common_ids <- Reduce(union, vectors_to_intersect)
```

## Cells kept/removed
```{r}
total_c <- format(n_distinct(cellsdata$cell_id), big.mark = ".", scientific = FALSE)
removed_c <- format(length(common_ids), big.mark = ".", scientific = FALSE)
cells_kept <- format(n_distinct(cellsdata$cell_id) - length(common_ids), big.mark = ".", scientific = FALSE)
pct_removed <- format(round(length(common_ids) / n_distinct(cellsdata$cell_id) * 100, 2), big.mark = ".", scientific = FALSE)
```

```{r}
library(scales)
total_c <- comma(ncol(sce))
removed_c <- comma(n_distinct(common_ids))

cells_kept <- comma(ncol(sce) - n_distinct(common_ids))

pct_removed <- round((n_distinct(common_ids) / ncol(sce) * 100), 2)
```

```{r}
# Set theme for all text elements to be black
theme_set(theme_minimal() +
  theme(
    plot.title = element_text(size = 20, color = "black"),
    plot.subtitle = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    legend.text = element_text(color = "black"),
    legend.title = element_text(color = "black"),
    strip.text = element_text(color = "black"),
    plot.tag = element_text(color = "black")
  )
)

# Assuming gg_counts and gg_b are your ggplot objects
wh(15, 10)
combined_plots <- wrap_plots(gg_counts, gg_b, nrow = 2) + 
plot_annotation(
  tag_levels = "A", 
  title = glue("N cells before QC: {total_c}; Cells removed: {length(common_ids)} / {pct_removed}%"))
```


```{r}
outdir <- glue("{plt_dir}/stamp_6")
if(!dir.exists(paste0(outdir))){
  dir.create(outdir)
}

pdf(paste0(outdir,"/QC1.pdf"), width = 15, height = 10)
combined_plots
dev.off()

pdf(paste0(outdir,"/QC1_mask.pdf"), width = 10, height = 10)
gg_mask + theme(text = element_text(size = 14))
dev.off()
```

```{r}
sce$low_quality <- "no"
sce$low_quality[sce$cell_id %in% common_ids] <- "yes" 
```

```{r}
sce_filt <- sce[,sce$low_quality == "no"]
```

```{r}
sce_filt
```

```{r}
qsave(sce_filt, glue("{res_dir}/sce_filt.qs"))
```

```{r}
sessionInfo()
```

