---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(scales)
})
```

```{r}
sub <- "Whole PBMCs"
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
res_dir <- paste0(proj_dir, "/data/stamp_6/CTC_1/processed")
sce <- qread(glue("{res_dir}/clust_sce.qs"), nthreads = 8)
```

```{r} 
sce
```

```{r}
pcs <- reducedDim(sce, "PCA")
rotation <- attr(pcs, "rotation")
first_pcs <- rotation[,1:20]
```

```{r}
first_pcs <- as.data.frame(first_pcs)
```

```{r}
pcs_list <- list()
for(i in 1:20){
  pcs_list[[i]] <- first_pcs[,i]
}
```

```{r}
for(i in 1:20){
  pcs_list[[i]] <- rotation[,i] %>% 
    as.data.frame() %>%
    rownames_to_column(var = "Gene") %>%
    rename(loading = ".") %>%
    arrange(desc(loading)) %>%
    mutate(PC = i)
}
```

```{r}
pcs_df <- bind_rows(pcs_list) %>%
          group_by(PC) %>%
          slice_head(n = 10)
```

```{r}

```













