---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(scales)
})
```

```{r}
sub <- "Whole PBMCs"
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
res_dir <- paste0(proj_dir, "/data/stamp_6/CTC_1/processed")
sce <- qread(glue("{res_dir}/clust_sce.qs"))
```


```{r}
markers <- qread(file = glue("{proj_dir}/data/pbmc_mcf7/mcf7_markers.qs"))
```


```{r}
flex_feat <- fread("/Users/emanuelepitino/Downloads/features.tsv.gz", sep = "\t", header = F)

data_dir <- glue("{proj_dir}/data/stamp_6/CTC_1/raw")
xenium_feat <- fread(glue("{data_dir}/cell_feature_matrix/features.tsv.gz"), sep = "\t", nThread = 3, header = F)
```


```{r}
feats <- markers$gene[markers$mean.logFC.cohen > 5]
```

```{r}
mcf7 <- markers[markers$cluster == "MCF7",]
feats <- mcf7$gene[1:200]
```

```{r}
ens_sign <- flex_feat %>%
              filter(V2 %in% feats) 
ens_sign <- ens_sign$V1
```

```{r}
inters <- intersect(ens_sign, xenium_feat$V1)
```


```{r}
mcf7_sign <- xenium_feat$V2[xenium_feat$V1 %in% inters]
```


```{r}
sign <- data.frame(gene = mcf7_sign, signature = "MCF7", mor = 1)
library(decoupleR)

ulm_start <- Sys.time()
res <- decoupleR::run_wsum(
    mat = counts(sce),
    network = sign,
    .source = "signature",
    .target = "gene",
    times = 20,
    .mor = "mor")

glue::glue("Time to run ulm is {round(difftime(Sys.time(), ulm_start, units = 's'), 0)} seconds")
```

```{r}
res$cell_id <- res$condition
```

```{r}
sce$score <- NA
sce$score[sce$cell_id %in% res$cell_id] <- res$score[match(sce$cell_id, res$cell_id)]
```

```{r}
df <- as.data.frame(colData(sce))

ggplot(df, aes(x = cell_area, y = score, color = sum)) + 
  geom_point(size = 0.01) +
  geom_vline(xintercept = 100, color = "red", linetype = "dashed" ) 
  #geom_hline(yintercept = 1, color = "red", linetype = "dashed")
```


```{r}
sce$inspect <- "no"
sce$inspect[sce$cell_area > 100 & sce$score > 1 & sce$sum > median(sce$sum)] <- "yes"
```

```{r}
sce$ctc <- res$score > 2
sce$score <- res$score
```

```{r}

```


```{r}
df <- as.data.frame(colData(sce))
wrap_plots(
plot_density(df,"score", "inspect", palette_general(), 50, "MCF7 score"),
plot_density(df,"cell_area", "inspect", palette_general(), 50, "MCF7 score"),
plot_density(df,"sum", "inspect", palette_general(), 50, "MCF7 score"),
nrow = 2)
```




















