---
title: "Analysis - Stamp_13a"
subtitle: "Emanuele Pitino"
date: "`r Sys.Date()`"
format: 
  html:
    theme: superhero
    smooth-scroll: true
    code-fold: true
    self-contained: true
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: true
  fig-width: 16     
  fig-height: 12 
---

### Libraries

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(dplyr)
library(here)
library(scater)
library(glue)
library(qs)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(spatstat)
library(InSituType)
})
```

### Data loading

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
stamp <- "stamp_13a"
res_dir <- glue("{proj_dir}/data/{stamp}/processed")
sce <- qread(glue("{res_dir}/anno_sce_P1.qs"), nthreads = 8)
```

```{r}
dir <- glue("{proj_dir}/data/{stamp}/Ist")
unsup <- qread(glue("{dir}/unsup.qs"))
```


```{r}
sce$label <- unsup$clust[colnames(sce)]
sce$label_prob <- unsup$prob[colnames(sce)]

pal_layout <- pal_s13a

pal <- Polychrome::createPalette(26,c("#99FFFF", "#FF99FF", "#FFFF99"))
names(pal) <- unique(sce$lvl1)
```

```{r}
cd <- as.data.frame(colData(sce))
```

```{r}
layout <- ggplot(cd, aes(x = CenterX_global_px, y = CenterY_global_px, color = sample)) +
  ggrastr::rasterise(geom_point(shape = 16, size = 0.001), dpi = 500) +
  scale_color_manual(values = pal_s13a) +
  labs(
    subtitle = "PBMCs perturbations",
    x = "x (px)",
    y = "y (px)"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 25, color = "black"),
   plot.subtitle = element_text(size = 22, color = "black"),
   axis.title  = element_text(size = 30),
   panel.grid = element_blank(),
   axis.text = element_blank(),
   axis.ticks = element_blank(),
   legend.title = element_text(size = 20),
   legend.text = element_text(size = 16)
  ) +
  coord_equal() +
  guides(color = guide_legend(override.aes = list(size = 6), ncol = 1)) +
  labs(color = "sub-STAMP")

pdf("/Users/emanuelepitino/Desktop/stamp_13a/layout.pdf")
layout
dev.off()
```

```{r}
df <- cd[,c("timepoint","experiment","lvl1")]
df <- as.data.frame(table(cd$experiment,cd$timepoint,cd$lvl1,cd$replicate)) %>%
  group_by(Var1,Var2,Var4) %>%
  mutate(pct = round(Freq / sum(Freq),4))

df$Var4 <- as.character(df$Var4)
df$Var4[df$Var4 == "r1"] <- "R.1"
df$Var4[df$Var4 == "r2"] <- "R.2"
df$Var4 <- factor(df$Var4, levels = c("R.1","R.2"))
prop <- ggplot(df, aes(x = Var4, y = pct, fill = Var3)) +
         geom_col() +
  scale_fill_manual(values = pal) +
  facet_grid(~Var2~Var1) +
  theme_bw() +
  theme(aspect.ratio = 2.5/1,
        text = element_text(size = 18, color ="black"),
        axis.text = element_text(color = "black", size = 15),
        axis.title = element_text(color = "black", size = 18),
        legend.text = element_text(size = 12)) +
  labs(x = "Replicate", y = "Proportion", fill = "Cell type") +
  scale_y_continuous(breaks = c(0.00,0.50,1))

pdf("/Users/emanuelepitino/Desktop/stamp_13a/Prop.pdf")
prop
dev.off()
```

## Identify TLR4 population in myeloid compartment and ctrl vs LPS
```{r}
sub <- sce[,sce$experiment %in% c("ctrl","LPS") & sce$lvl0 == "myeloid"]
feats <- c("TLR1","TLR2","TLR3","TLR4","TLR5",
           "TLR7","TLR8")

tlr4_pos <- plotDots(sub, group = "lvl1", features = feats,
         scale = T, center = T) +
  theme(aspect.ratio = 3/1) +
  scale_color_gradient2("z-scored\nmean expr.", low = "blue4", mid = "grey90", high = "red4") +
  scale_size_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, 0.5),
    range = c(1, 5)  # Increase these numbers to make dots bigger
  ) +
  theme_minimal(6) +
  theme(
    aspect.ratio = 1.5/1,
    axis.text.y = element_text(color = "black", size = 8),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1,
      color = "black",
      size = 7
    ),
    panel.grid.major = element_line(linewidth = 0.1, color = "lightgrey"),
    axis.title = element_blank(),
    legend.key.size = unit(0.5, "lines") 
  ) +
  coord_flip()

pdf("/Users/emanuelepitino/Desktop/stamp_13a/tlr4_pos.pdf", height = 2) # ctrl and lps only
tlr4_pos
dev.off()
```

# Check TLR4 expression in CTRL and LPS experiments in act. mono.

```{r}
sub <- sce[,sce$experiment %in% c("ctrl","LPS") & sce$lvl1 == "act. mono."]
feats <- c("TLR1","TLR2","TLR3","TLR4","TLR5",
           "TLR7","TLR8")

tlr4_act_mono <- plotDots(sub, group = "sample", features = "TLR4",
         scale = F, center = T) +
  theme(aspect.ratio = 3/1) +
  scale_color_gradient2("z-scored\nmean expr.", low = "blue4", mid = "grey90", high = "red4") +
  scale_size_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, 0.5),
    range = c(1, 5)  # Increase these numbers to make dots bigger
  ) +
  theme_minimal(6) +
  theme(
    aspect.ratio = 1.5/1,
    axis.text.y = element_text(color = "black", size = 8),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1,
      color = "black",
      size = 7
    ),
    panel.grid.major = element_line(linewidth = 0.1, color = "lightgrey"),
    axis.title = element_blank(),
    legend.key.size = unit(0.5, "lines") 
  ) +
  coord_flip()

tlr4_act_mono

#pdf("/Users/emanuelepitino/Desktop/stamp_13a/tlr4_pos.pdf", height = 2) # ctrl and lps only
#tlr4_pos
#dev.off()
```

```{r}
sub <- sce[,sce$lvl1 == "act. mono." & sce$experiment != "aCD3aCD28"]


feats <- c(
  # Early Response Genes (4h)
  "TNF", "IL1B", "IL6", "IL8", "CXCL8", "IL12A", "IL12B",
  "CCL2", "CCL3", "CCL4", "CXCL10", "PTGS2", "NOS2",
  "NFKBIA", "FOS", "JUN", "EGR1", "CD80", "CD86", "CD40",
  
  # Late Response Genes (24h)
  "IL10", "TGFB1", "IFNB1", "IFIT1", "IFIT2", "IFIT3",
  "OAS1", "OAS2", "OAS3", "SOCS1", "SOCS3", "IRF1", "IRF7",
  "HLA-DRA", "HLA-DRB1", "CD83", "MMP9", "VEGFA",
  
  # Common Genes (Both Time Points)
  "NFKB1", "RELA", "SOD2", "TNFAIP3"
)

plotDots(sub, group = "sample", features = intersect(feats, rownames(sce)),
         scale = F, center = T) +
  theme(aspect.ratio = 3/1) +
  scale_color_gradient2("centered\nmean expr.", low = "blue4", mid = "grey90", high = "red4") +
  scale_size_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, 0.5),
    range = c(1, 5)  # Increase these numbers to make dots bigger
  ) +
  theme_minimal(6) +
  theme(
    aspect.ratio = 1/6,
    axis.text.y = element_text(color = "black", size = 8),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1,
      color = "black",
      size = 7
    ),
    panel.grid.major = element_line(linewidth = 0.1, color = "lightgrey"),
    axis.title = element_blank(),
    legend.key.size = unit(0.5, "lines") 
  ) +
  coord_flip()
```

