---
title: "Exploratory - clustering - Stamp 7b - ESCs"
subtitle: "Emanuele Pitino"
date: "`r Sys.Date()`"
format: 
  html:
    theme: superhero
    smooth-scroll: true
    code-fold: true
    self-contained: true
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: true
  fig-width: 16     
  fig-height: 12 
---

### Libraries

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(dplyr)
library(here)
library(scater)
library(glue)
library(qs)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(InSituType)
})
```

### Data loading

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
stamp <- "stamp_7b"
sample <- "iESC"
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))

res_dir <- glue("{proj_dir}/data/{stamp}/{sample}")
sce <- qread(glue("{res_dir}/clust_sce.qs"), nthreads = 8)
#sce <- sce[,sample(colnames(sce),1000)]
sce 
```

```{r}
dir <- glue("{proj_dir}/data/{stamp}/{sample}/Ist")
dir.create(dir, showWarnings = F, recursive = T)
unsup <- qread(glue("{dir}/unsup.qs"))
```


```{r}
sce$label <- unsup$clust[colnames(sce)]
sce$label_prob <- unsup$prob[colnames(sce)]
pal <- Polychrome::createPalette(26, c("#fc6060", "#74f774", "#7c7cfc"))
names(pal) <- unique(sce$label)
```

## Cell numbers

```{r}
df <- as.data.frame(table(sce$label)) %>%
  mutate(Proportion = round((Freq / sum(Freq)) * 100, 2))

ggplot(df, aes(x = Var1, y = Freq)) + 
  geom_col(aes(fill = Var1)) +
  geom_text(aes(label = Freq), vjust = -0.5, size = 5) +
  scale_fill_manual(values = pal) + 
  theme_bw() +
  theme(text = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 15, color = "black"),
        panel.grid = element_blank()) +
  labs(fill = "Sample", y = "# Cells") +
  labs(x = "Cluster", fill = "Cluster")
```

## Density plot

```{r}
library(spatstat)
# Define the window 
df <- as.data.frame(colData(sce))
x_range <- range(df$CenterX_global_px, na.rm = TRUE)
y_range <- range(df$CenterY_global_px, na.rm = TRUE)
win <- owin(xrange = x_range, yrange = y_range)

# Convert your dataframe to a point pattern (ppp) object within the specified window
df_ppp <- ppp(df$CenterX_global_px, df$CenterY_global_px, window = win)

density_obj <- density(df_ppp)

# Convert the density object to a data frame for ggplot
density_df <- as.data.frame(as.table(as.matrix(density_obj)))

# Plot the density with ggplot2
ggplot(density_df, aes(x = Var1, y = Var2, fill = Freq)) +
  geom_raster() +
  scale_fill_viridis_c() + # For better color scaling, using viridis color map
  coord_fixed() +
  labs(
    title = "Density of Spatial Point Pattern",
    subtitle = glue("Chisq quadrat test: {format(quadrat_test$p.value, digits = 2, scientific = TRUE)}"),
    x = "X Coordinate",
    y = "Y Coordinate",
    fill = "Density"
  ) +
  theme_minimal()
```

## Label transfer probability in space
```{r}
df <- as.data.frame(colData(sce))
df <- df[sample(rownames(df)),]

 ggplot(df, aes(x = CenterX_global_px, y = CenterY_global_px, color = label_prob)) + 
  scale_color_gradientn(colours = c("navy","red4")) +
  ggrastr::rasterise(geom_point(size = 0.1, shape = 16), dpi = 800) +
  theme_bw() + 
  theme(panel.grid = element_blank(), text = element_text(colour = "black", size = 20), 
        axis.text = element_text(colour = "black", size = 15)) +
  labs(x = "x_px", y = "y_px") +
  coord_equal() +
  labs(color = "IST prob")
```

## Clusters proportion/Sample
```{r}
df <- as.data.frame(table(sce$sample,sce$label)) %>%
      group_by(Var1) %>%
      mutate(Proportion = round((Freq / sum(Freq)) * 100, 2))

ggplot(df, aes( x = Var1 , y = Proportion, fill = Var2)) + 
  geom_col() +
  scale_fill_manual(values = pal) +
  theme_bw() +
  theme(text = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 15, color = "black"),
        panel.grid = element_blank()) +
  labs(x = "Sample", fill = "Cluster")
```

## Space
```{r}
df <- as.data.frame(colData(sce))
df <- df[sample(rownames(df)),]

 ggplot(df, aes(x = CenterX_global_px, y = CenterY_global_px, color = label)) + 
  scale_color_manual(values = pal) +
  ggrastr::rasterise(geom_point(size = 0.1, shape = 16), dpi = 600) +
  theme_bw() + 
  theme(panel.grid = element_blank(), text = element_text(colour = "black", size = 20), 
        axis.text = element_text(colour = "black", size = 15)) +
  labs(x = "x_px", y = "y_px") +
  guides(color = guide_legend(override.aes = list(size = 4))) +
   coord_equal() +
   labs(color = "Cluster")
```


## FlightPath
```{r}
fp_layout <- flightpath_layout(logliks = unsup$logliks, profiles = unsup$profiles)

gg_fp <- ggplot(fp_layout$cellpos, aes(x = x, y = y, color = fp_layout$clust)) +
  ggrastr::rasterise(geom_point(size = 0.1, shape = 16), dpi = 800) +
  scale_color_manual(values = pal) +
  theme_bw() +
    theme(text = element_text(size = 15, color = "black"),
          axis.text = element_text(size = 10, color = "black"),
          panel.grid = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(color = "Cluster", title = glue("FlightPath - {stamp} - {sample}")) +
  guides(color = guide_legend(override.aes = list(size = 4))) 

gg_fp
```


## InSituType Profiles

Normalize & log-transform the profiles
```{r}
norm <- unsup$profiles /  Matrix::colSums(unsup$profiles) # normalize
lognorm <- log1p(norm) + 1e-6  # log transform
```

Calculate logFC

```{r}
result <- lognorm 
for (i in 1:nrow(lognorm)) {
  for (j in 1:ncol(lognorm)) {
    result[i, j] <- lognorm[i, j] / mean(lognorm[i, -j])
  }
}
```

Take first 10 features for each cluster by logFC

```{r}
feat <- unique(as.vector(unlist(apply(result, 2, function(column) {
  names(sort(column, decreasing = TRUE))[1:10]
}))))
```

Remove outliers at 2.5 sd for better visualization

```{r}
x <- result[feat,]

z <- \(x, th=2) {
    if (is.null(dim(x))) {
        x[x < 0] <- 0
        sd <- sd(x, na.rm=TRUE)
        x <- x-mean(x, na.rm=TRUE)
        if (sd != 0) x <- x/sd
    } else {
        mus <- colMeans(x)
        sds <- colSds(x)
        x <- sweep(x, 2, mus, `-`)
        x <- sweep(x, 2, sds, `/`)
    }
    x[x > +th] <- +th
    x[x < -th] <- -th
    return(x)
}
mtx_scaled <- z(x)
```

Plot

```{r}
# Perform hierarchical clustering on euclidean distance matrix with "average" method
column_dist_euclidean <- dist(mtx_scaled, method = "euclidean")
column_hclust_complete <- hclust(column_dist_euclidean, method = "average")

# Create the heatmap
color_function <- circlize::colorRamp2(c(min(mtx_scaled), 0, max(mtx_scaled)), c("navy", "white", "red"))
hm <- ComplexHeatmap::Heatmap(t(mtx_scaled),
              name = "expression",
              cluster_rows = F,
              cluster_columns = as.dendrogram(column_hclust_complete),
              show_row_names = TRUE,
              show_column_names = TRUE,
              show_row_dend = FALSE,
              show_column_dend = FALSE,
              col = color_function,
              row_names_side = "left",
              height = unit(4,"cm"),
              column_names_gp = grid::gpar(fontsize = 8),
              row_order = match(c("b","c","a","i","e","d","f","k","h","g","j"), rownames(t(mtx_scaled))))

hm
```

### Umap
```{r}
ggrastr::rasterise(plotReducedDim(sce,"UMAP", color_by = "label",point_size = 0.01,
               scattermore = F, rasterise = F) +
    scale_color_manual(values = pal) + 
    guides(color = guide_legend(override.aes = list(alpha = 1, size = 4))) +
    labs(color = "Cluster"),
  dpi = 800)
```

```{r}
sessionInfo()
```




