---
title: "Unsupervised clustering - InSituType Stamp_3 c100"
subtitle: "Emanuele Pitino"
date: "`r Sys.Date()`"
format: 
  html:
    theme: superhero
    smooth-scroll: true
    code-fold: true
    self-contained: true
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
params:
  sample: !expr NA
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: true
---

### Libraries

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(InSituType)
})
```

### Data loading

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
stamp <- "stamp_3"
#sample <- params$sample
sample <- "c100"
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))

res_dir <- glue("{proj_dir}/data/{stamp}/processed/{sample}")
sce <- qread(glue("{res_dir}/qc_{sample}.qs"), nthreads = 8)
#sce <- sce[,sample(colnames(sce),1000)]
sce 
```


#### Run IST unsupervised clustering

```{r}
ist <- function(sce, nk, gs=TRUE, pbs=NULL, bkg=TRUE) {
    # dependencies
    library(InSituType)
    library(SingleCellExperiment)
    # load counts
    mtx <- counts(sce[gs, ])
    mtx <- as(t(mtx), "dgCMatrix")
    # cohorting based on IF data
    j <- names(cd <- colData(sce))
    i <- grep("^Mean", j, value=TRUE)
    i <- setdiff(i, "Mean.G")
    i <- c("Area", "AspectRatio", i)
    coh <- fastCohorting(as.matrix(cd[i]))
    # background estimation
    neg <- grep("^neg", altExpNames(sce), value=TRUE)
    neg <- sce$nCount_negprobes/nrow(altExp(sce, neg))
    # update reference profiles
    pbs <- if (!is.null(pbs)) {
        bkg <- if (bkg) {
            rna <- sce$nCount_RNA
            rna*mean(neg)/mean(rna) 
        }
        updateReferenceProfiles(
            reference_profiles=pbs, counts=mtx,
            neg=neg, bg=bkg)$updated_profiles
    }
    # clustering
    insitutype(mtx, 
        reference_profiles=pbs,
        update_reference_profiles=FALSE,
        neg=neg, cohort=coh, n_clusts=nk)
}
```

```{r}
unsup <- ist(sce, 3:3)
```

## Save
```{r}
dir <- glue("{proj_dir}/data/{stamp}/{sample}/Ist")
dir.create(dir, showWarnings = F, recursive = T)
qsave(unsup, file = glue("{dir}/unsup.qs"))
```

```{r}
sessionInfo()
```
