---
title: "Unsupervised clustering - InSituType"
format: 
  html:
    code-fold: true
    self-contained: true
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: true
  fig-width: 16     
  fig-height: 12 
---

### Libraries

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(InSituType)
})
```

### Data loading

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
stamp <- "stamp_3"
sample <- "PBMCs"
res_dir <- glue("{proj_dir}/data/{stamp}/{sample}")
sce <- qread(glue("{res_dir}/PreProcNew.qs"), nthreads = 8)
```

#### Run IST unsupervised clustering

```{r}
counts <- t(counts(sce))
neg <- t(counts(altExp(sce,"negprobes")))
negmean <- Matrix::rowMeans(neg)
```

```{r}
unsup <- insitutype(
  x = counts,
  neg = negmean,
  bg = NULL,
  n_clusts = c(3:8),
  reference_profiles = NULL, # for Unsupervised
)
```

#### Profiles HeatMap

```{r}
hm <- heatmap(sweep(unsup$profiles, 1, 
                    pmax(apply(unsup$profiles, 1, max), .2), "/"), scale = "none",
        main = "Cluster mean expression profiles")
hm
```

#### FlightPath

```{r}
fp_layout <- flightpath_layout(logliks = unsup$logliks, profiles = unsup$profiles)

gg_fp <- ggplot(fp_layout$cellpos, aes(x = x, y = y, color = fp_layout$clust)) +
  ggrastr::rasterise(geom_point(size = 0.1, shape = 16), dpi = 800) +
  scale_color_brewer(palette = "Set2") +
  theme_bw() +
    theme(text = element_text(size = 15, color = "black"),
          axis.text = element_text(size = 10, color = "black"),
          panel.grid = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(color = "Cluster", title = glue("FlightPath - {stamp} - {sample}")) +
  guides(color = guide_legend(override.aes = list(size = 4))) 

gg_fp
```

#### Save

```{r}
plot_dir <- glue("{plt_dir}/{stamp}/{sample}/Ist")
dir.create(plot_dir, showWarnings = F, recursive = T)

pdf(glue("{plot_dir}/Unsup.pdf"), width = 10, height = 10)
heatmap(sweep(unsup$profiles, 1, pmax(apply(unsup$profiles, 1, max), .2), "/"), scale = "none",
        main = glue("Cluster expression profiles - {stamp} - {sample}"))
gg_fp
dev.off()
```

```{r}
dir <- glue("{proj_dir}/data/{stamp}/{sample}/Ist")
dir.create(dir, showWarnings = F, recursive = T)
qsave(unsup, file = glue("{dir}/unsup.qs"))
```

```{r}
sessionInfo()
```
