---
title: "Level2 annotation - stamp11"
subtitle: "Emanuele Pitino"
date: "`r Sys.Date()`"
format: 
  html:
    theme: superhero
    smooth-scroll: true
    code-fold: true
    self-contained: true
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
params:
  sample: !expr NA
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: true
---
```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
})
```

```{r}
dir <- glue("{here()}")
# Parameters and paths
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
stamp <- "stamp_11"
sub <- "PBMCs"
lin <- "Myeloid"
sce <- qread(glue("{proj_dir}/data/{stamp}/{sub}/processed/{lin}/clust_sce.qs"), nthreads = 8)
```


```{r}
pal <- Polychrome::createPalette(26,c("#99FFFF", "#FF99FF", "#FFFF99"))
names(pal) <- unique(sce$label)
```

## Clusters analysis
```{r}
myeloid <-  c("IL1B","FCGR3A","CD14","CD1C","CCR2","CD68","ITGAM","CD34","FLT3","CX3CR1","CLEC9A","CCR5",
          "S100A8","S100A9","LYZ","ITGAX", "IL3RA","CD1C","MZB1")

monocyte <- c("CD14", "CD68", "CD163", "CCR2", "CCR5", "CD33", "CD36", "FCGR3A", "CD86", "CD80", "CSF1R", "CX3CR1", "CXCL9", "CXCL10", "CXCL11", "CD1C", "CLEC10A", "CLEC9A", "FCER1A", "AXL", "CD22", "DAB2", "SIGLEC6", "IL3R", "LILRA4", "IRF8")

feat <- unique(c(myeloid,monocyte))
gg_clust1 <- create_plots2(sce, "label", feat)


pdf("/Users/emanuelepitino/Desktop/stamp11/myeloid.pdf", width = 18, height = 8)
gg_clust1
dev.off()
```

```{r}
df <- as.data.frame(colData(sce))
gg_clust_2 <- wrap_plots(
    plot_density(df, "sum", "label", pal, "Counts",2000),
    plot_density(df, "detected", "label", pal, "Features",1000),
    plot_density(df, "cell_area", "label", pal, "Cell Area",500),
    plot_density(df, "nucleus_area", "label", pal, "Nucleus Area",80),
    ncol = 2, nrow = 2) +
plot_annotation(tag_levels = "A")
```

## Annotation
Here we want to distinguish main lineages such as T/B lymphocytes and Myeloid cells.
```{r}
sce$lvl2[sce$label == "1"] <- "class. mono."
sce$lvl2[sce$label == "2"] <- "class. mono."
sce$lvl2[sce$label == "3"] <- "non-class. mono."
sce$lvl2[sce$label == "4"] <- "non-class. mono."
sce$lvl2[sce$label == "5"] <- "DC4"
sce$lvl2[sce$label == "6"] <- "int. mono."
sce$lvl2[sce$label == "13"] <- "int. mono."
sce$lvl2[sce$label == "7"] <- "infl. mono."
sce$lvl2[sce$label == "8"] <- "infl. mono."
sce$lvl2[sce$label == "9"] <- "infl. mono."
sce$lvl2[sce$label == "10"] <- "class. mono."
sce$lvl2[sce$label == "11"] <- "DC1/DC2/DC5"
sce$lvl2[sce$label == "12"] <- "pDC"
```

```{r}
res_dir <- glue("{proj_dir}/data/{stamp}/{sub}/processed/{lin}")
qsave(sce, glue("{res_dir}/lvl2_sce.qs"), nthreads = 8)
```
