---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
})
```

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```


```{r}
res_dir <- paste0(proj_dir, "/data/stamp_1/processed")
sce <- qread(glue("{res_dir}/clust_sce.qs"), nthreads = 8)
```

```{r}
sce$label <- factor(sce$label, levels = c(1,2,3,4,5,6,7,8))
```

```{r}
pal <- palette_general()
length(pal) <- length(unique(sce$label))
names(pal) <- unique(sce$label)
```

## Clusters analysis
```{r}
df <- as.data.frame(colData(sce))
gg_clust2 <- wrap_plots(
    plot_density(df, "sum", "label", pal, "Counts",500),
    plot_density(df, "detected", "label", pal, "Features",300),
    plot_density(df, "Area.um2", "label", pal, "Cell Area",500),
  #  plot_density(df, "nucleus_area", "label", pal, "Nucleus Area",500),
    ncol = 2, nrow = 2) +
plot_annotation(tag_levels = "A")
```

## Differential expression
```{r}
sce$label <- as.factor(sce$label)
markers <- scoreMarkers(sce, sce$label, BPPARAM = bp)
```

```{r}
# Clean markers list
transform_marker <- function(marker_df, cluster_name) {
  marker_df <- as.data.frame(marker_df) %>%
    select(median.logFC.detected, self.detected) %>%
    arrange(desc(self.detected)) %>%
    #filter(median.logFC.cohen > 0.25) %>%
    mutate(gene = rownames(.), cluster = as.numeric(cluster_name))
  rownames(marker_df) <- NULL
  return(marker_df)
}

# Apply the function to each element of the markers list along with their names
markers <- mapply(transform_marker, markers, names(markers), SIMPLIFY = FALSE)

markers <- bind_rows(markers) %>%
  arrange(cluster,desc(median.logFC.detected), .by_group = TRUE) 

markers$median.logFC.detected <- round(markers$median.logFC.detected, 2)
```

```{r}
top <- markers %>%
            group_by(cluster) %>%
            slice_head(n = 5)
feats <- top$gene
```


```{r}
feats <- as.character(unique(feats))
feats <-  c("TCF7","RGCC","DUSP2","SPOCK2","IL7R","NKG7","GNLY","CCL5","GZMH","PRF1",
                                  "IGHM","MS4A1","CD74","IGHD","P2RX5",
                                  "S100A4","FCER1G","PSAP","S100A9","CXCL8","SAT1","LMNA","DUSP2","ANXA1",
                                  "PSCA","INS","KRT80","BMP7","MB")
```

```{r}
gg_clust1_markers <- create_plots2(sce, "label", feats, pal)
```

## Annotation
Here we want to distinguish main lineages such as T/B lymphocytes and Myeloid cells.
```{r}
sce$lvl1[sce$label == "1"] <- "B"
sce$lvl1[sce$label == "2"] <- "T"
sce$lvl1[sce$label == "3"] <- "T"
sce$lvl1[sce$label == "4"] <- "LowQ"
sce$lvl1[sce$label == "5"] <- "T"
sce$lvl1[sce$label == "6"] <- "T"
sce$lvl1[sce$label == "7"] <- "Myeloid"
sce$lvl1[sce$label == "8"] <- "T"
sce$lvl1[sce$label == "3"] <- "T"
sce$lvl1[sce$label == "3"] <- "T"

```

```{r}
sce$lvl1 <- factor(sce$lvl1, levels = c("T","B","Myeloid","LowQ"))
```


```{r}
pal_lvl1 <- c(pal_lvl1, "LowQ" = "grey")
```

```{r}
# A
gg_anno1 <- create_plots2(sce, "lvl1", feats, pal_lvl1)

# B
df <- as.data.frame(colData(sce))
gg_anno2 <- wrap_plots(
    plot_density(df, "sum", "lvl1", pal_lvl1, "Counts",500),
    plot_density(df, "detected", "lvl1", pal_lvl1, "Features",300),
    plot_density(df, "Area.um2", "lvl1", pal_lvl1, "Cell Area",500),
    ncol = 2, nrow = 2) +
plot_annotation(tag_levels = "A")
```





```{r}
outdir <- glue("{plt_dir}/stamp_1")
if(!dir.exists(paste0(outdir))){
  dir.create(outdir)
}
pdf(paste0(outdir,"/lvl1.pdf"), width = 12, height = 8)
gg_clust1_markers
gg_clust2
gg_anno1
gg_anno2
dev.off()
```


```{r}
qsave(sce, glue("{res_dir}/lvl1_sce.qs"), nthreads = 8)
```
