---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(scales)
})
```

```{r}
sub <- "Whole PBMCs"
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
res_dir <- paste0(proj_dir, "/data/stamp_6/CTC_1/processed")
sce_full <- qread(glue("{res_dir}/clust_sce.qs"))
```

```{r} 
sce_full
```

# Subset higher outliers for cell area
```{r}
out_area <- isOutlier(sce_full$cell_area, nmads = 2, log = T, type = "higher")
table(out_area)
```

```{r}
df <- as.data.frame(colData(sce)) %>%
        filter(sum > mean(sce$sum) & cell_area > attr(out_area,"threshold")["higher"])
nrow(df)
```

```{r}
df <- df %>%
      arrange(desc(cell_area))
```


```{r}
#ids <- df$cell_id[1:100]
sce <- sce_full[,sce_full$cell_id %in% df$cell_id[1:100]]
```

```{r}
feats <- c("AKT1","ANPEP","ARID1A","ATM","BRAF","CDK1","CDK12","CDK2","CDK4","CDK6",
           "CDKN1A","CDKN1B","CDKN1C","CDKN2A","CDKN2B","CDKN2C","CDKN2D","CENPV","CENPF",
           "CFC1","CTSD","CTSW","CTSS","GRBB2","GRBB3","GRBB4","GATA2","GATA3","TP53","VEGFA",
           "CD3E","CD247","CD19","CD79A","CD79B","CD74","NKG7","NCAM1","FCGR3A","CD14","CD8A","CD8B","CD4")
```

```{r}
iter <- 1
```

```{r}
idx <- c(1:100,101:200,201:300,301:400,401:500,501:600,601:700,
         701:800,801:900,901:1000)
```


```{r}
iter <- 1
idx_list <- list(
  1:100, 101:200, 201:300, 301:400, 401:500,
  501:600, 601:700, 701:800, 801:900, 901:1000
)

for(i in idx_list){

sce <- sce_full[,sce_full$cell_id %in% df$cell_id[i]]
sce <- logNormCounts(sce, subset.row = NULL, BPPARAM = bp)

dec.var <- modelGeneVar(sce, BPPARAM = bp)
hvg <- getTopHVGs(dec.var,fdr.threshold =  0.9)
length(hvg)

dec.var$hvg <- "no"
dec.var$hvg[rownames(dec.var) %in% hvg] <- "yes"
table(dec.var$hvg)

rowData <- rowData(sce)
dec.var$Symbol <- ""
dec.var$Symbol[rownames(dec.var) %in% rowData$ID] <- rowData$Symbol

gg_hvg <- plot_hvg(dec.var, sub)
gg_hvg

set.seed(101001)
sce <- fixedPCA(sce, subset.row = hvg,BSPARAM=IrlbaParam())

wh(6,5)
num_pcs_to_retain <- 20
percent.var <- attr(reducedDim(sce), "percentVar")

# Create a data frame for ggplot
data <- data.frame(PC = 1:length(percent.var), Variance = percent.var)

# Plot using ggplot2
gg_var <- ggplot(data, aes(x = PC, y = Variance)) +
  geom_point() +
  scale_y_log10() +
  xlab("PC") +
  ylab("Variance explained (%)") +
  geom_vline(xintercept = num_pcs_to_retain, color = "red") +
  theme_bw()
#gg_var

reducedDim(sce, "PCA") <-  reducedDim(sce, "PCA")[,1:num_pcs_to_retain]
wh(6,5)
gg_pca <- plotPCA(sce, point_size = 2.5, scattermore = TRUE) + ggtitle("PCA")
#gg_pca

# Run UMAP
set.seed(123)
sce <- runUMAP(sce, dimred="PCA", BPPARAM = bp)

wh(6,5)
gg_um <- plotReducedDim(sce, "UMAP", point_size = 2.5, scattermore = TRUE) 
gg_um

wh(12,10)
combined <- wrap_plots(gg_var, gg_pca, gg_um, ncol = 2, nrow = 2) +
  plot_annotation(tag_levels = "A") + 
  plot_annotation(title = glue("Stamp 6 - {sub} + CTCs"), subtitle = glue("N = {comma(ncol(sce))} cells"))


# Build SNN graph
snn.gr <- buildSNNGraph(sce, type = "jaccard", BNPARAM=AnnoyParam(), use.dimred="PCA", BPPARAM = bp)

# Run Leiden
clusters <- igraph::cluster_louvain(snn.gr, resolution = 1)

# Assign labels
sce$label <- as.character(clusters$membership)
table(sce$label)

gg_clust <- plotReducedDim(sce, "UMAP", colour_by ="label", point_size = 2.5, text_by = "label", rasterise = F)

combined <- wrap_plots(gg_var, gg_pca, gg_clust, gg_hvg, ncol = 2, nrow = 2) +
  plot_annotation(tag_levels = "A") + 
  plot_annotation(title = glue("Stamp 6 - {sub} + CTCs - It er: {iter}"), subtitle = glue("N = {comma(ncol(sce))} cells"))

gg_hm <- plotHeatmap(sce, features = intersect(feats, rownames(sce)),
            order_columns_by = "label", center = T, main = "test")

gg_violin <- plotColData(sce, x = "label", y = "cell_area", color_by = "sum") + scale_y_log10()

pdf(glue("{plt_dir}/stamp_6/IterCTC/Iter_{iter}.pdf"), width = 10, height = 10)
print(gg_hm)
print(combined)
print(gg_violin)
dev.off()

iter <- iter +1
}
```


```{r}
"TFF1","SPTSSB","AREG","MDK","PSMD6","ACKR3","EEF1A2","USP32","GATA3"
```


```{r}
grep("GATA3", rownames(sce), value =T )
```












