---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(scales)
})
```

```{r}
sub <- "Whole PBMCs"
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
res_dir <- paste0(proj_dir, "/data/stamp_6/CTC_1/processed")
sce <- qread(glue("{res_dir}/ctc_sce.qs"))
```


```{r}
library(ggplot2)
library(dplyr)

# Assuming 'sce' is already defined and contains the 'Cell_Type' variable
# and the function plotReducedDim is defined appropriately

# Create a data frame from the SingleCellExperiment object
umap_data <- as.data.frame(reducedDim(sce, "UMAP"))
umap_data$Cell_Type <- sce$Cell_Type

# Separate the data for CTC and other cell types
umap_data_pbmc <- umap_data %>% filter(Cell_Type != "CTC")
umap_data_ctc <- umap_data %>% filter(Cell_Type == "CTC")

# Plot the UMAP with PBMCs first and then CTCs on top
ggplot() +
  geom_point(data = umap_data_pbmc, aes(x = UMAP1, y = UMAP2, color = Cell_Type), size = 0.5) +
  geom_point(data = umap_data_ctc, aes(x = UMAP1, y = UMAP2, color = Cell_Type), size = 0.6) +
  scale_color_manual(values = pal) +
  theme_minimal() +
  labs(x = "UMAP1", y = "UMAP2", color = "Cell Type")
```

```{r}
df <- as.data.frame(colData(sce))
```


```{r}
sce$tst <- "PBMCs"
sce$tst[sce$cell_area > 250] <- "CTC"
```


```{r}
# Separate the data for CTC and other cell types
df_pbmc <- df %>% filter(tst != "CTC")
df_ctc <- df %>% filter(tst == "CTC")

# Plot the PBMCs first and then CTCs on top
ggplot() +
  geom_point(data = df_pbmc, aes(x = x_centroid, y = y_centroid, color = tst), size = 0.5) +  # Adjust size as needed
  geom_point(data = df_ctc, aes(x = x_centroid, y = y_centroid, color = tst), size = 0.6) +   # Adjust size as needed
  scale_color_manual(values = pal) +
  theme_minimal() +
  labs(x = "", y = "", color = "Cell Type")
```


```{r}
# Separate the data for CTC and other cell types
df_pbmc <- df %>% filter(Cell_Type != "CTC")
df_ctc <- df %>% filter(Cell_Type == "CTC")

# Plot the PBMCs first and then CTCs on top
ggplot() +
  geom_point(data = df_pbmc, aes(x = x_centroid, y = y_centroid, color = Cell_Type), size = 0.5) +  # Adjust size as needed
  geom_point(data = df_ctc, aes(x = x_centroid, y = y_centroid, color = Cell_Type), size = 0.6) +   # Adjust size as needed
  scale_color_manual(values = pal) +
  theme_minimal() +
  labs(x = "", y = "", color = "Cell Type")
```

```{r}
grep("EGF", rownames(sce), value = T)
```


```{r}
plotDots(sce, features = intersect(c("AREG","GATA3","EGFR","CD3E","CD247","CD19","CD79A","CD79B","NGK7","NCAM1",
                           "CD1C","EGF","EGFR","VEGFA"), rownames(sce)), group = "Cell_Type", scale =TRUE, center = TRUE) +
    coord_flip() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```



```{r}
```


```{r}
```











