---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
library(InSituType)
})
```

### Libraries

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

### Data loading

```{r}
stamp <- "stamp_3"
sample <- "PBMCs"
res_dir <- glue("{proj_dir}/data/{stamp}/{sample}")
sce <- qread(glue("{res_dir}/PreProcNew.qs"), nthreads = 8)
unsup <- qread(glue("{res_dir}/Ist/unsup.qs"))
```

### QC on Unsup clustering

unassigned cells with assigned probability \< 0.8

```{r}
sce$clust <- unsup$clust
sce$prob <- unsup$prob
sce$clust[sce$prob < 0.8] <- "Unassigned"
```

```{r}
pal <- palette_general()
length(pal) <- length(unique(sce$clust))
names(pal) <- unique(sce$clust)
```

## Differential expression

```{r}
#sce <- logNormCounts(sce, BPPARAM = bp)
sce$clust <- as.factor(sce$clust)
markers <- scoreMarkers(sce, sce$clust, BPPARAM = bp)
```

```{r}
# Clean markers list
transform_marker <- function(marker_df, cluster_name) {
  marker_df <- as.data.frame(marker_df) %>%
    select(median.logFC.detected, self.detected) %>%
    arrange(desc(self.detected)) %>%
    #filter(median.logFC.cohen > 0.25) %>%
    mutate(gene = rownames(.), cluster = as.character(cluster_name))
  rownames(marker_df) <- NULL
  return(marker_df)
}

# Apply the function to each element of the markers list along with their names
markers <- mapply(transform_marker, markers, names(markers), SIMPLIFY = FALSE)

markers <- bind_rows(markers) %>%
  arrange(cluster,desc(median.logFC.detected), .by_group = TRUE) 

markers$median.logFC.detected <- round(markers$median.logFC.detected, 2)
markers <- markers %>% filter(median.logFC.detected > 0.10)
```

```{r}
library(openxlsx)

# Assuming your data frame is named 'markers'
# Split the data frame by 'cluster'
clusters <- split(markers, markers$cluster)

# Create a new Excel workbook
wb <- createWorkbook()

# Add each subset of the data frame as a separate sheet
for (cluster_name in names(clusters)) {
  addWorksheet(wb, cluster_name)
  writeData(wb, sheet = cluster_name, clusters[[cluster_name]])
}

# Save the workbook to a file
mrk_dir <- glue("{markers_dir}/{stamp}/{sample}")
dir.create(mrk_dir, showWarnings = F, recursive = T)
saveWorkbook(wb, file = glue("{mrk_dir}/markers_{sample}.xlsx"), overwrite = TRUE)
```

```{r}
palette_general <- function(){
  
  set.seed(1234) # for reproducibility
  color_palette <- Polychrome::createPalette(25, c("#fc6060", "#74f774", "#7c7cfc"))
  return(unname(color_palette))
}

pal <- palette_general()
names(pal) <- unique(sce$clust)
```

```{r}
top <- markers %>%
            group_by(cluster) %>%
            arrange(desc(median.logFC.detected)) %>%
            slice_head(n = 15)
feats <- top$gene
```

```{r}
gg_combined_clust <- create_plots2(sce, "clust", feats, pal)
```

```{r}
df <- as.data.frame(colData(sce))
gg_dens_clust <- wrap_plots(
                  plot_density(df, "sum", "clust", pal, "nCounts",500),
                  plot_density(df, "detected", "clust", pal, "nFeatures",300),
                  plot_density(df, "Area.um2", "clust", pal, "Area",500),
                  ncol =2)
```

```{r}
sce$lvl1[sce$clust == "Unassigned"] <- "Unassigned"
sce$lvl1[sce$clust %in% c("a","c","f","g")] <- "Myeloid"
sce$lvl1[sce$clust == "d"] <- "B"
sce$lvl1[sce$clust %in% c("b","e")] <- "T"
```

## Differential expression

```{r}
markers <- scoreMarkers(sce, sce$lvl1, BPPARAM = bp)
```

```{r}
# Clean markers list
transform_marker <- function(marker_df, cluster_name) {
  marker_df <- as.data.frame(marker_df) %>%
    select(median.logFC.detected, self.detected) %>%
    arrange(desc(self.detected)) %>%
    #filter(median.logFC.cohen > 0.25) %>%
    mutate(gene = rownames(.), cluster = as.character(cluster_name))
  rownames(marker_df) <- NULL
  return(marker_df)
}

# Apply the function to each element of the markers list along with their names
markers <- mapply(transform_marker, markers, names(markers), SIMPLIFY = FALSE)

markers <- bind_rows(markers) %>%
  arrange(cluster,desc(median.logFC.detected), .by_group = TRUE) 

markers$median.logFC.detected <- round(markers$median.logFC.detected, 2)
markers <- markers %>% filter(median.logFC.detected > 0)
```

```{r}
top <- markers %>%
            group_by(cluster) %>%
            slice_head(n = 10)
feats <- top$gene
```

```{r}
pal <- palette_general()
names(pal) <- unique(sce$lvl1)
```

```{r}
gg_combined <- create_plots2(sce, "lvl1", feats, pal)
```

```{r}
df <- as.data.frame(colData(sce))
gg_density <- wrap_plots(
                plot_density(df, "sum", "lvl1", pal, "nCounts",500),
                plot_density(df, "detected", "lvl1", pal, "nFeatures",500),
                plot_density(df, "Area.um2", "lvl1", pal, "Area",500),
                ncol =2)
```

```{r}
dir <- glue("{plt_dir}/{stamp}/{sample}")
pdf(glue("{dir}/Ist/Lvl1.pdf"), width = 15, height = 8)
gg_combined_clust
gg_dens_clust
gg_combined
gg_density
dev.off()
```

```{r}
qsave(sce, glue("{res_dir}/sce_ist1.qs"), nthreads = 8)
qsave(markers, glue("{res_dir}/markers_lvl1.qs"))
```
