---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
})
```

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

```{r}
res_dir <- paste0(proj_dir, "/data/stamp_1/processed")
sce <- qread(glue("{res_dir}/lvl1_sce.qs"), nthreads = 8)
```


```{r}
df <- as.data.frame(colData(sce))
```

# 1. Counts
```{r}
pal <- pal_lvl1
```


```{r}
wh(15,8)
qc_metrics <- wrap_plots(
    plot_density(df, "nCount_RNA", pal_lvl1, "Counts",300),
    plot_density(df, "nFeature_RNA", pal_lvl1, "Features",300),
    plot_density(df, "Area.um2", pal_lvl1, "Cell Area",500),
    ncol = 2, nrow = 2) +
plot_annotation(tag_levels = "A")
```

# 2. Correlation of gene expression from Flex

```{r}
flex <- readRDS("/combined_annotated_flex_pbmc.rds")
```


```{r}
```


```{r}
```

