---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(glue)
library(qs)
library(parallel)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(data.table)
})
```

```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```


```{r}
res_dir <- paste0(proj_dir, "/data/stamp_5/processed")
sce <- qread(glue("{res_dir}/clust_sce.qs"))
```


```{r}
pal <- palette_general()
length(pal) <- length(unique(sce$label))
names(pal) <- unique(sce$label)
```

## Clusters analysis
```{r}
gg_clust1 <- create_plots2(sce, "label", intersect(feats_xenium, rownames(sce)))

df <- as.data.frame(colData(sce))
gg_clust2 <- wrap_plots(
    plot_density(df, "sum", "label", pal, "Counts",200),
    plot_density(df, "detected", "label", pal, "Features",150),
    plot_density(df, "cell_area", "label", pal, "Cell Area",500),
    plot_density(df, "nucleus_area", "label", pal, "Nucleus Area",500),
    ncol = 2, nrow = 2) +
plot_annotation(tag_levels = "A")
```

## Annotation
Here we want to distinguish main lineages such as T/B lymphocytes and Myeloid cells.
```{r}
sce$lvl1[sce$label == "1"] <- "T"
sce$lvl1[sce$label == "2"] <- "LowQ"
sce$lvl1[sce$label == "3"] <- "T"
sce$lvl1[sce$label == "4"] <- "LowQ"
sce$lvl1[sce$label == "5"] <- "Myeloid"
sce$lvl1[sce$label == "6"] <- "T"
sce$lvl1[sce$label == "7"] <- "LowQ" # i know it's NK, but we want to group with T for the moment
sce$lvl1[sce$label == "8"] <- "B"
sce$lvl1[sce$label == "9"] <- "Myeloid"
sce$lvl1[sce$label == "10"] <- "Myeloid"
sce$lvl1[sce$label == "11"] <- "T"

```

```{r}
sce$lvl1 <- factor(sce$lvl1, levels = c("T","B","Myeloid", "LowQ"))
```


```{r}
pal_lvl1 <- c(pal_lvl1, "LowQ" = "grey")
```

```{r}
# A
gg_anno1 <- create_plots2(sce, "lvl1", intersect(feats_xenium, rownames(sce)))

# B
df <- as.data.frame(colData(sce))
gg_anno_2 <- wrap_plots(
    plot_density(df, "sum", "lvl1", pal_lvl1, "Counts",200),
    plot_density(df, "detected", "lvl1", pal_lvl1, "Features",150),
    plot_density(df, "cell_area", "lvl1", pal_lvl1, "Cell Area",500),
    plot_density(df, "nucleus_area", "lvl1", pal_lvl1, "Nucleus Area",500),
    ncol = 2, nrow = 2) +
plot_annotation(tag_levels = "A")
```

```{r}
outdir <- glue("{plt_dir}/stamp_5")
if(!dir.exists(paste0(outdir))){
  dir.create(outdir)
}
pdf(paste0(outdir,"/lvl1.pdf"), width = 12, height = 8)
gg_clust1
gg_clust2
gg_anno1
gg_anno_2
dev.off()
```


```{r}
qsave(sce, glue("{res_dir}/lvl1_sce.qs"), nthreads = 8)
```
