---
title: "Slingshot - Flex - Stamp 7b - Combined"
subtitle: "Emanuele Pitino"
date: "`r Sys.Date()`"
format: 
  html:
    theme: superhero
    smooth-scroll: true
    code-fold: true
    self-contained: true
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: true
  fig-width: 12     
  fig-height: 9 
---

## Setup
### Libraries
```{r}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(dplyr)
library(here)
library(scater)
library(scuttle)
library(scran)
library(glue)
library(qs)
library(scales)
library(bluster)
})
```

### Paths
```{r}
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))

sample <- "combined"
#sample <- "iESC_0h"
stamp <- "Stamp_7b"
#npcs <- params$npcs
dir <- glue("{here()}")
source(glue("{dir}/scripts/misc/paths.R"))
source(glue("{dir}/scripts/misc/BIN.R"))
```

### Load data
```{r}
base_dir <- glue("{proj_dir}/data/{stamp}/processed/flex/{sample}")
sce <- qread(glue("{base_dir}/clust_sce.qs"), nthreads = 8)
sce
```

```{r}
library(slingshot)
sce.sling <- slingshot(sce, reducedDim='HARMONY', clusterLabels = sce$label)

embedded <- embedCurves(sce.sling, "UMAP_integ")
embedded <- slingCurves(embedded)[[2]] # only 1 path.
embedded <- data.frame(embedded$s[embedded$ord,])

plotReducedDim(sce.sling, "UMAP_integ", colour_by="slingPseudotime_1", scattermore = T) +
    geom_path(data=embedded, aes(x=UMAP1, y=UMAP2), size=1.2)

plotUMAP(sce.sling, colour_by = "sample", scattermore = T)

```









